### ISSUE TITLE
Can be zsh-autosuggestions suppressed for one command?

### ISSUE THREAD

**Issue by psprint** [zsh-users/zsh-autosuggestions#193] opened 2016-09-06 21:13 UTC
I have a plugin that assigns to BUFFER. Text appears at command line, and zsh-autosuggestions quickly proposes a continuation. Can I suppress this? I put into BUFFER a complete command that doesn't need continuation, seeing the propositions makes it harder to read the command.

**PS.** Also, when I tried to follow the command assigned to BUFFER with "#" hoping that comment context will stop zsh-autosuggestion, what happened is:

``` zsh
cd /Users/sgniazdowski/.zplugin/plugins/zsh-users---zsh- #cd /Users/sgniazdowski/.zplugin/plugins/zsh-users---zsh-syntax-highlighting/highlighters/main
```

I.e. a suggestion including whole considered text appeared after "#"

It would be really great to be able to set ZSH_AUTOSUGGESTIONS_SKIP=1 and have clean command line for one entry, otherwise reading the command is a pain :|

**Comment by psprint** [comment] 2016-09-13 06:23
Hello again,
I now use a small program that uses TIOCSTI to feed input to Zsh:

https://github.com/psprint/zconvey/blob/master/feeder/feeder.c#L15-L25

It works slow because of autosuggestions, and say "artifacts" of suggested text are visible during sending of command. So again, could something like `ZSH_AUTOSUGGESTIONS_SKIP_ONE=1` be added?

**Comment by ericfreese** [comment] 2016-10-01 23:07
> when I tried to follow the command assigned to BUFFER with "#" hoping that comment context will stop zsh-autosuggestion ... a suggestion including whole considered text appeared after "#"

This definitely shouldn't be happening. It would be helpful if you can isolate this problem. Does it happen with no other plugins loaded? What version of z-asug are you using? What version of zsh? etc.

> I have a plugin that assigns to BUFFER. Text appears at command line, and zsh-autosuggestions quickly proposes a continuation. Can I suppress this?

Would it solve your problem to add the name of the plugin widget that assigns to `BUFFER` to [the list of widgets to clear the suggestion](https://github.com/zsh-users/zsh-autosuggestions/blob/master/src/config.zsh#L17)? I think that would prevent z-asug from giving a suggestion after your widget is run.

```shell
% function my-widget() { BUFFER="hello world" }
% zle -N my-widget
% bindkey '^I' my-widget
% ZSH_AUTOSUGGEST_CLEAR_WIDGETS=($ZSH_AUTOSUGGEST_CLEAR_WIDGETS my-widget)
```

**Comment by ericfreese** [comment] 2016-10-01 23:39
> I now use a small program that uses TIOCSTI to feed input to Zsh ... It works slow because of autosuggestions

Interesting. I wonder if this is the cause of the delay when using z-asug with Midnight Commander as reported in #136.

I'm hoping that performance issues like this will be fixed with #170.

**Comment by balta2ar** [comment] 2017-02-18 20:02
@psprint I'm not sure, but do you think https://github.com/zsh-users/zsh/blob/master/Functions/Zle/bracketed-paste-magic could help?

**Comment by psprint** [comment] 2017-09-25 16:44
After working with [Zshelldoc](https://github.com/zdharma/zshelldoc) and using `zsh-autosuggestions.zsh` as a test file, I started to understand your code. I now would be able to investigate, however:
 - The autosuggestions' switch to asynchronous (via `zpty`) fetching solved all problems.

So the issue can be closed, I think. Or maybe it would be useful to mute `zsh-autosuggestions` till next `precmd` hook.

**Closed** 2017-09-26 14:38 UTC
