### ISSUE TITLE
no suggestions are shown in new terminal session

### ISSUE THREAD

**Issue by iiison** [zsh-users/zsh-autosuggestions#407] opened 2019-03-04 04:03 UTC
I can see the suggestions only in same session, if I quit the terminal then no suggestions are shown.

**Comment by ericfreese** [comment] 2019-03-04 06:32
Check out my comment on #405. Are you describing the same issue?

**Comment by iiison** [comment] 2019-03-07 07:42
@ericbn I followed the instructions you provided in SO page. I added:

```
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
```

in my `~/.zshrc` file, but I still can't see the suggestions.

**Comment by ericbn** [comment] 2019-03-07 11:34
@iiison, you mentioned a different Eric, but let me give you my two cents here.  :- )

These are the history options I use (besides HISTFILE, HISTSIZE and SAVEHIST), and they work well with zsh-autosuggestions:

```
setopt HIST_IGNORE_ALL_DUPS # removes older command from the history if a duplicate is to be added.
setopt HIST_IGNORE_DUPS     # does not enter immediate duplicates into the history.
setopt HIST_IGNORE_SPACE    # removes commands from the history that begin with a space.
setopt HIST_SAVE_NO_DUPS    # ommits older commands that duplicate newer ones when saving.
setopt HIST_VERIFY          # doesn't execute the command directly upon history expansion.
setopt SHARE_HISTORY        # causes all terminals to share the same history 'session'.
```

**Comment by ericfreese** [comment] 2019-03-08 00:24
Is history working ok otherwise? If you press the up arrow while in your the session, do you see commands you entered in the previous session?

**Comment by iiison** [comment] 2019-03-08 02:56
@ericfreese the Up arrow shows history in same window, but nothing happens in new window.

**Comment by iiison** [comment] 2019-03-08 03:11
@ericbn eh, I didn't see the name, I've just typed eric 😄 

I added the configs you suggested in my file, but, still it's not working.

**Comment by heydluv** [comment] 2019-03-26 11:54
@iiison Maybe you need to add it to your list of plugins on Line 89 of your `.zshrc` file.

**Comment by ericfreese** [comment] 2019-04-01 21:40
I'm going to go ahead and close this, since it seems it's not related to this plugin, but is caused by something in your config. Get history working properly and the plugin should start working as well.

**Closed by ericfreese** 2019-04-01 21:40 UTC
Labels: support

**Comment by iiison** [comment] 2019-04-03 06:42
@ericfreese you were right, there was nothing wrong with zsh-autosuggestions. The problem was the zsh_history file permission. I changed the ownership to my user name from root. and now it's working fine. If anybody else faces the same issue, I used this command to change the ownership:

```sh
$ sudo chown $USER $HISTFILE
```
