### ISSUE TITLE
Cursor won't jump at the end of line

### ISSUE THREAD

**Issue by PapiCZ** [zsh-users/zsh-autosuggestions#452] opened 2019-06-23 13:22 UTC
If I write following command:
```
systemctl lis<cursor>(t-unit-files)
```
, then after pressing right arrow I will get following behavior:
```
systemctl list<cursor>-unit-files
```
, but expected behavior is following:
```
systemctl list-unit-files<cursor>
```

This bug occurs only in `0.6.2-1`. Version `0.6.1-1` works as expected.

**Comment by gruberma** [comment] 2019-06-23 16:30
I got the same problem.

The issue was introduced in commit 676aebd by setting the cursor to `max_cursor_pos` instead of `#BUFFER`.

```diff
- CURSOR=${#BUFFER}
+ CURSOR=${max_cursor_pos}
```

where `max_cursor_pos` is equal to the length of the buffer before the suggestion is appended.
Hence the cursor stays where it is.

The problem also exists when using vi-keybindings.

**Comment by ericfreese** [comment] 2019-06-23 18:21
Thanks guys, major oversight on my part. Will get this fixed soon. And will get a test written up for this so it should never happen again.

**Comment by ericfreese** [comment] 2019-06-23 18:51
Ok please try branch `fixes/move-cursor-on-accept` (PR #453). It should fix this issue and maintain the fixed behavior for #302 as well.

**Comment by proYang** [comment] 2019-06-24 05:02
I also encountered the same problem, please fix it as soon as possible.:rose:

**Comment by woefe** [comment] 2019-06-24 07:47
`fixes/move-cursor-on-accept` works for me. The cursor jumps to the end and `dl` works as intended.

**Comment by mustafacansevinc** [comment] 2019-06-24 09:02
> `fixes/move-cursor-on-accept` works for me. The cursor jumps to the end and `dl` works as intended.

I second that.

**Comment by thornycrackers** [comment] 2019-06-24 19:49
@ericfreese Thanks for resolving this so quickly

**Closed** 2019-06-24 23:36 UTC
Labels: bug, reproduced
