### ISSUE TITLE
Keybinding not working in IntelliJ embedded terminal

### ISSUE THREAD

**Issue by vickyliuyi** [zsh-users/zsh-autosuggestions#326] opened 2018-05-11 21:01 UTC
Hi, 

I tried to add the `bindkey '^[[Z' autosuggest-accept  ` to make shift+tab work like the right arrow key to accept the suggestions. I tried type that directly and also added that into my .zshrc files. I'm using zsh with the Mac built-in terminal. It turns out it worked fine if I opened a regular terminal window but not working at all in the IntelliJ embedded terminal window. 
Any idea what might be wrong?

Thanks!

**Comment by ericfreese** [comment] 2018-05-14 19:27
Can you bind shift + tab to any other widgets in the IntelliJ terminal?

**Comment by ericfreese** [comment] 2018-05-15 21:14
Going to go ahead and close this as I'd guess the problem is unrelated to this plugin.

**Closed by ericfreese** 2018-05-15 21:14 UTC
Labels: support

**Comment by gloryVine** [comment] 2021-04-05 00:11
I'm having the same issue three years later. I disabled all other keymaps of shift-tab in PyCharm's settings, and it's still not working.
