### ISSUE TITLE
sources ~/.zshrc as well as type <space> then the shell would be broken

### ISSUE THREAD

**Issue by clay-f** [zsh-users/zsh-autosuggestions#205] opened 2016-11-05 01:38 UTC
i like this plugins,  it's fast and practicality.
i was  using oh-my-zsh
add the zsh-autosuggestions to zsh plugins
i was `source ~/.zshrc` and then type everything + space and shell broken right away every time as same

this plugins
    `plugins=(zsh-autosuggestions zsh-syntax-highlighting git z rails)`
config
   `bindkey '^ ' autosuggest-accept`

**Comment by caesar** [comment] 2016-12-19 00:12
I'm not sure if the exact nature of this problem is understandable from @clay-f's description, but the issue is simple:

If zsh-autosuggestions is enabled, then sourcing the `.zshrc` file once zsh is already running will cause zsh to crash when the next key is pressed.

I'm not sure why exactly this happens, since sourcing `zsh-autosuggestions` itself multiple times does not cause the problem.

**Comment by caesar** [comment] 2016-12-19 00:16
Okay, playing with this a bit, and for me the issue seems to be a combination of `zsh-autosuggestions` and `zsh-syntax-highlighting`.

Specifically, the problem is triggered by sourcing `zsh-syntax-highlighting` a second time, but *only if `zsh-autosuggestions` has already been sourced.*

So I'm not sure which module actually has the bug…

**Comment by caesar** [comment] 2016-12-19 00:24
Upon further research this seems to be a dupe of #126 so should probably be closed in favour of that thread.

**Comment by clay-f** [comment] 2016-12-19 11:33
oh, thanks, i have tried <a href="https://github.com/zsh-users/zsh-autosuggestions/issues/126">#123</a>
but not make sense,

**Comment by clay-f** [comment] 2016-12-19 11:40
@caesaroh, thanks, i have tried <a href="https://github.com/zsh-users/zsh-autosuggestions/issues/126">#123</a>
reference 
`danielshahaf`
```
_zsh_autosuggest_start() {
        _zsh_autosuggest_check_deprecated_config
        _zsh_autosuggest_bind_widgets
+       add-zsh-hook -d precmd _zsh_autosuggest_start
 }
autoload -Uz add-zsh-hook
```
`make`
but not make sense, 

seem there is not  clear point to fixed that issue ?

**Comment by caesar** [comment] 2016-12-19 13:55
@clay-f I haven't actually tried the solution there, but I managed to work around it by only sourcing 
`zsh-syntax-highlighting` when the profile is loaded at shell startup, and not when it is sourced again, like this (in my `.zshrc`):

```zsh
if [[ $ZSH_EVAL_CONTEXT == 'file' ]]; then
	source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi
```

**Comment by clay-f** [comment] 2016-12-19 14:02
@caesar `zsh-syntax-highlighting` and `zsh-autosuggestions` same time sourcing ?

**Closed** 2017-02-18 06:37 UTC
Labels: duplicate
