### ISSUE TITLE
Hello! I've updated Mac OS Sierra, but can not be used iTerm

### ISSUE THREAD

**Issue by jiangguoliang** [zsh-users/zsh-autosuggestions#195] opened 2016-09-22 13:00 UTC
Hello! I've updated Mac OS Sierra, but can not be used iTerm

Last login: Thu Sep 22 20:51:15 on ttys001
/Users/jiangguoliang/.oh-my-zsh/tools/check_for_upgrade.sh:3: failed to load module `zsh/datetime': dlopen(/usr/lib/zsh/5.0.8/zsh/datetime.so, 9): image not found
_current_epoch:1: bad math expression: operand expected at `/ 60 / 60 ...'
/Users/jiangguoliang/.oh-my-zsh/lib/completion.zsh:11: failed to load module `zsh/zle': dlopen(/usr/lib/zsh/5.0.8/zsh/zle.so, 9): image not found
/Users/jiangguoliang/.oh-my-zsh/lib/completion.zsh:22: failed to load module `zsh/zle': dlopen(/usr/lib/zsh/5.0.8/zsh/zle.so, 9): image not found
/Users/jiangguoliang/.oh-my-zsh/lib/completion.zsh:26: command not found: zstyle
/Users/jiangguoliang/.oh-my-zsh/lib/completion.zsh:29: failed to load module `zsh/zle': dlopen(/usr/lib/zsh/5.0.8/zsh/zle.so, 9): image not found
/Users/jiangguoliang/.oh-my-zsh/lib/completion.zsh:31: command not found: zstyle
/Users/jiangguoliang/.oh-my-zsh/lib/completion.zsh:32: command not found: zstyle
/Users/jiangguoliang/.oh-my-zsh/lib/completion.zsh:37: command not found: zstyle
/Users/jiangguoliang/.oh-my-zsh/lib/completion.zsh:41: command not found: zstyle
/Users/jiangguoliang/.oh-my-zsh/lib/completion.zsh:44: command not found: zstyle
/Users/jiangguoliang/.oh-my-zsh/lib/completion.zsh:45: command not found: zstyle
/Users/jiangguoliang/.oh-my-zsh/lib/completion.zsh:48: command not found: zstyle
/Users/jiangguoliang/.oh-my-zsh/lib/completion.zsh:59: command not found: zstyle
/Users/jiangguoliang/.oh-my-zsh/lib/functions.zsh:104: failed to load module `zsh/langinfo': dlopen(/usr/lib/zsh/5.0.8/zsh/langinfo.so, 9): image not found
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:7: failed to load module `zsh/terminfo': dlopen(/usr/lib/zsh/5.0.8/zsh/terminfo.so, 9): image not found
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:18: command not found: bindkey
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:20: command not found: bindkey
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:21: command not found: bindkey
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:22: command not found: bindkey
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:23: failed to load module `zsh/terminfo': dlopen(/usr/lib/zsh/5.0.8/zsh/terminfo.so, 9): image not found
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:26: failed to load module `zsh/terminfo': dlopen(/usr/lib/zsh/5.0.8/zsh/terminfo.so, 9): image not found
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:31: failed to load module `zsh/terminfo': dlopen(/usr/lib/zsh/5.0.8/zsh/terminfo.so, 9): image not found
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:37: failed to load module `zsh/terminfo': dlopen(/usr/lib/zsh/5.0.8/zsh/terminfo.so, 9): image not found
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:43: failed to load module `zsh/terminfo': dlopen(/usr/lib/zsh/5.0.8/zsh/terminfo.so, 9): image not found
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:46: failed to load module `zsh/terminfo': dlopen(/usr/lib/zsh/5.0.8/zsh/terminfo.so, 9): image not found
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:50: command not found: bindkey
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:52: command not found: bindkey
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:53: command not found: bindkey
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:55: failed to load module `zsh/terminfo': dlopen(/usr/lib/zsh/5.0.8/zsh/terminfo.so, 9): image not found
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:59: command not found: bindkey
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:60: failed to load module `zsh/terminfo': dlopen(/usr/lib/zsh/5.0.8/zsh/terminfo.so, 9): image not found
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:63: command not found: bindkey
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:64: command not found: bindkey
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:65: command not found: bindkey
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:70: failed to load module `zsh/zle': dlopen(/usr/lib/zsh/5.0.8/zsh/zle.so, 9): image not found
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:71: command not found: bindkey
/Users/jiangguoliang/.oh-my-zsh/lib/key-bindings.zsh:74: command not found: bindkey
/Users/jiangguoliang/.oh-my-zsh/lib/theme-and-appearance.zsh:2: colors: function definition file not found
/Users/jiangguoliang/.oh-my-zsh/oh-my-zsh.sh:77: compinit: function definition file not found
/Users/jiangguoliang/.oh-my-zsh/plugins/git/git.plugin.zsh:2: command not found: zstyle
/Users/jiangguoliang/.oh-my-zsh/plugins/git/git.plugin.zsh:76: command not found: compdef
/Users/jiangguoliang/.oh-my-zsh/plugins/git/git.plugin.zsh:87: command not found: compdef
/Users/jiangguoliang/.oh-my-zsh/plugins/git/git.plugin.zsh:94: command not found: compdef
/Users/jiangguoliang/.oh-my-zsh/plugins/git/git.plugin.zsh:103: command not found: compdef
/Users/jiangguoliang/.oh-my-zsh/plugins/git/git.plugin.zsh:113: command not found: compdef
/Users/jiangguoliang/.oh-my-zsh/plugins/git/git.plugin.zsh:123: command not found: compdef
/Users/jiangguoliang/.oh-my-zsh/plugins/git/git.plugin.zsh:132: command not found: compdef
/Users/jiangguoliang/.oh-my-zsh/plugins/git/git.plugin.zsh:138: command not found: compdef
/Users/jiangguoliang/.oh-my-zsh/plugins/git/git.plugin.zsh:141: command not found: compdef
/Users/jiangguoliang/.oh-my-zsh/plugins/git/git.plugin.zsh:144: command not found: compdef
/Users/jiangguoliang/.oh-my-zsh/plugins/git/git.plugin.zsh:147: command not found: compdef
/Users/jiangguoliang/.oh-my-zsh/plugins/git/git.plugin.zsh:156: command not found: compdef
/Users/jiangguoliang/.oh-my-zsh/plugins/git/git.plugin.zsh:159: command not found: compdef
/Users/jiangguoliang/.oh-my-zsh/plugins/git/git.plugin.zsh:161: command not found: compdef
/Users/jiangguoliang/.oh-my-zsh/plugins/git/git.plugin.zsh:175: command not found: compdef
/Users/jiangguoliang/.oh-my-zsh/plugins/git/git.plugin.zsh:186: command not found: compdef
/Users/jiangguoliang/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh:111: command not found: zle
/Users/jiangguoliang/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh:341: command not found: zle
/Users/jiangguoliang/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh:342: command not found: zle
/Users/jiangguoliang/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh:343: command not found: zle
/Users/jiangguoliang/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh:444: add-zsh-hook: function definition file not found
zsh: failed to load module `zsh/zle': dlopen(/usr/lib/zsh/5.0.8/zsh/zle.so, 9): image not found
☁  ~

**Comment by george-b** [comment] 2016-09-22 15:47
This does not look like an issue with the autosuggestions plugin. Looks more like your zsh install is borked.

It would seem Sierra ships with zsh 5.2, so I'm not sure what's referencing 5.0.8 as seen in your output.

https://www.reddit.com/r/MacOS/comments/4oqskk/could_you_do_me_a_favor/d4etdns

Also that fact you see `command not found: zstyle` indicates zsh isn't running as that's a shell built-in.

**Comment by jaimehrubiks** [comment] 2016-09-27 23:38
Isn't working for me neither.

**Comment by ericfreese** [comment] 2016-10-01 22:32
Going to go ahead and close this issue because it doesn't look like the z-asug plugin is at fault here. Feel free to re-open if you determine that there is in fact a problem with this plugin and have some new information on how to reproduce.

**Closed by ericfreese** 2016-10-01 22:32 UTC

**Comment by Taivas** [comment] 2016-10-08 04:57
I got the same problem. Find `/usr/share/zsh/5.0.8/functions` in `~/.zshrc` and replace it to `/usr/share/zsh/5.2/functions` then thing should go fine.
