### ISSUE TITLE
_zsh_autosuggest_async_response:6: failed to close file descriptor 16: bad file descriptor

### ISSUE THREAD

**Issue by alok** [zsh-users/zsh-autosuggestions#353] opened 2018-07-02 18:29 UTC
@ericfreese I get this using your improved completion branch every time it tries to bring up a completion on Ubuntu 18.04.

**Comment by ericfreese** [comment] 2018-07-02 18:36
Thanks @alok 

Can you reproduce this using `zsh -f` and sourcing the plugin manually?

What version of zsh are you using?

I've just merged that branch into `develop`. Can you confirm that the problem still exists on the latest commit in `develop`. If so, can you send the git commit sha that you're using?

**Comment by alok** [comment] 2018-07-09 17:35
I'm using the latest commit from `develop`. Doesn't seem to arise if I do it with `zsh -f`, so now I'm wondering what could be up.

**Comment by ericfreese** [comment] 2018-07-09 20:29
Interesting. It would be very helpful if you could iteratively comment out lines from your zshrc and start a new shell to narrow down exactly what is causing the issue.

**Comment by alok** [comment] 2018-07-11 18:54
This seems to be the offending line: `bindkey " " expand-alias`. If I try to run a minimal zshrc that only has that line and sources the plugin, I get this error:

```



/home/ubuntu/zshrc-tmp:1: job table full or recursi
on limit exceeded
/home/ubuntu/.config/zsh/zsh-autosuggestions/zsh-au
tosuggestions.zsh:42: job table full or recursion l
imit exceeded
/home/ubuntu/.config/zsh/zsh-autosuggestions/zsh-au
tosuggestions.zsh:444: job table full or recursion
limit exceeded
add-zsh-hook:15: job table full or recursion limit
exceeded
add-zsh-hook:89: job table full or recursion limit
exceeded
```

**Comment by ericfreese** [comment] 2018-07-13 16:49
Thanks @alok. It looks like even just this zshrc will cause it:

```sh
foobar() {
  zle self-insert
}

zle -N foobar
bindkey ' ' foobar

source zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_USE_ASYNC=true
```

**Comment by ericfreese** [comment] 2018-07-14 03:51
Should be fixed on `develop`.

**Closed by ericfreese** 2018-07-14 03:51 UTC
Labels: bug, reproduced
