### ISSUE TITLE
Partial accept not working on vi-forward-word when in vi-mode normal mode

### ISSUE THREAD

**Issue by kolyuchiy** [zsh-users/zsh-autosuggestions#188] opened 2016-08-19 08:09 UTC
It only accepts until the end of current word but not further.
But if I do `bindkey '^[f' vi-forward-word` then it works correctly in insert mode.

**Comment by swalladge** [comment] 2016-10-12 07:35
I'm having the same problem. It also seems to buggily work sometimes - for example if I alternate between hitting the keys for vi-forward-blank-word and vi-forward-blank-word-end it will partial accept up to a certain point. It seems to be a problem with being in `vicmd` mode - even doing something like `bindkey -M vicmd '^[f' vi-forward-word` won't work.

**Comment by IngoHeimbach** [comment] 2017-11-15 06:10
For whatever reason, the cursor position must be increased by one if a vi widget partially accepted a suggestion (see my [patch](https://github.com/IngoHeimbach/zsh-autosuggestions/commit/af25faed003de1557b9e2e74173f4c58ed80101a)). I don't know if this is the proper way of solving this issue but it seems to work.

**Comment by toadjaune** [comment] 2018-05-04 16:10
Just ran into this bug myself, and I think I found a [cleaner fix](https://github.com/zsh-users/zsh-autosuggestions/pull/324).

The issue is that in vicmd keymap, the cursor is _on_ the last character of the line, instead of right _after_ it. This is an issue since it breaks an assumption made by the code to check whether we went further than the initial buffer size or not.

My fix simply uses an intermediate variable for the check, that is incremented by 1 in `vicmd` keymap, thus restoring the usual behaviour of the test.
Moreover, we don't change the actual CURSOR value, which prevents any weird side-effect from happening.

For some reason that I don't undersand yet, this seems to also fix the issue in `visual` keymap.

**Comment by ericfreese** [comment] 2018-05-14 21:52
See my comment on @toadjaune's PR here: https://github.com/zsh-users/zsh-autosuggestions/pull/324#issuecomment-388974152

What are people expecting to happen when you use `vi-forward-word` vs. `vi-forward-word-end`?

`vi-forward-word` moves the cursor to the first character of the next word. Would you actually expect that character to be accepted (added to the buffer)?

**Comment by ericfreese** [comment] 2018-05-15 18:25
Should be fixed on `develop` branch. Will go out with next release.

**Closed by ericfreese** 2018-05-15 18:25 UTC
Labels: bug, pull-request-welcome
