### ISSUE TITLE
_zsh_autosuggest_modify:27: unrecognized modifier `0'

### ISSUE THREAD

**Issue by fenfei** [zsh-users/zsh-autosuggestions#250] opened 2017-05-26 02:19 UTC
Hi,
I got this error 

_zsh_autosuggest_modify:27: unrecognized modifier `0'

when I type something in the command line after source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

My linux is RedHat 5.3
zsh version is 5.0.7

I cannot update anything because i don't have the permission...

**Comment by hmny** [comment] 2017-07-07 19:07
Having the same problem in RLEL.

**Comment by ericfreese** [comment] 2017-08-11 17:12
I'm not able to reproduce this on zsh 5.0.7 on Mac OS X. Not sure what might be going on here. Can you reproduce without loading your config?

```shell
% zsh -f
%% source zsh-autosuggestions.zsh
```

**Comment by donkeyx** [comment] 2017-08-17 05:53
I am having exactly the same issue. As soon as i enable it, i will get that error: 

sourcing the autosuggestions file manually : 
[1]    22789 segmentation fault  zsh -f

uname -a : 
Linux hostname-here 2.6.32-504.12.2.el6.x86_64 #1 SMP Wed Mar 11 11:14:39 CDT 2015 x86_64 x86_64 x86_64 GNU/Linux

zsh --version 
zsh 4.3.10 (x86_64-unknown-linux-gnu)

**Comment by ilcn** [comment] 2017-08-18 04:54
same issue. fortunately I left another ssh session open otherwise I would've been fxxked.

**Comment by donkeyx** [comment] 2017-08-18 04:57
@ilcn I repaired my hosts by :: sftp -> rm .zshrc, then log back in an try again. Happened randomly on a few servers 👍

**Comment by yar00001** [comment] 2017-08-18 05:03
@ericfreese yeah it works fine on Mac or Ubuntu. I'm having this problem only on RHEL.

**Comment by suyinlong** [comment] 2017-09-19 06:03
Same problem on RHEL5

cat /etc/redhat-release
Red Hat Enterprise Linux Server release 5.3 (Tikanga)

zsh --version
zsh 5.0.2 (x86_64-unknown-linux-gnu)

**Comment by yar00001** [comment] 2017-09-20 16:43
Any plan to fix this bug?

**Comment by ericfreese** [comment] 2017-09-21 14:43
Would be happy to fix but currently unable to reproduce. Maybe someone running RHEL can dig in a little bit?

**Comment by ilcn** [comment] 2017-09-21 19:32
I will load RHEL5.6 (the one I had trouble with) into a vm and try it. 

Meanwhile let me say this: this plugin is not necessary if you just auto complete. zsh has that for you. Just type something and use arrow keys to bring zsh suggestions (not automatically like this plugin does very nicely). I found this satisfies my need mostly.

**Comment by hsiehju** [comment] 2017-11-08 23:44
If you didn't have another ssh session, you can also do this.

I was not able to sftp because I printed out some messages in my rc.

ssh -t $HOST "bash -l"

**Comment by hsiehju** [comment] 2017-11-09 01:05
Just a quick fix, but change the string on this line: https://github.com/zsh-users/zsh-autosuggestions/blob/master/src/widgets.zsh#L66

The string should be: `"${orig_postdisplay[0,1]}.added"` instead of `"${orig_postdisplay:0:$#added}"`

I think it has to do with an older version of Bash that did used different string modifiers.

GNU bash, version 4.1.2
zsh 4.3.10

**Comment by zhugaozi** [comment] 2018-10-02 05:02
I repaired it when i upgrade cento OS from version 6.3 to version 6.10

**Comment by ericfreese** [comment] 2018-12-17 04:43
Was able to reproduce this in v4.3.10. Not currently a supported version of zsh, but I'll see what I can do to support it.

**Comment by ericfreese** [comment] 2019-07-03 04:12
I'm going to go ahead and close this since it's related to running a non-supported version of zsh. Fix is to upgrade to zsh at least v4.3.11.

**Closed by ericfreese** 2019-07-03 04:12 UTC
Labels: enhancement, pull-request-welcome

**Comment by jakubLangr** [comment] 2019-08-01 17:12
I have `zsh 5.7.1 (x86_64-apple-darwin15.6.0)` and am getting this error.
