### ISSUE TITLE
Accept suggestion sometimes eats leading space

### ISSUE THREAD

**Issue by henrebotha** [zsh-users/zsh-autosuggestions#357] opened 2018-07-10 07:56 UTC
Suppose I type this:

```zsh
$ scripts/deploy.sh
```

Zsh-autosuggestions suggests this:

```zsh
$ scripts/deploy.sh 123.234.32.1
```

But if I press <kbd>→</kbd> to accept it, **sometimes** (I'm not sure what the condition is here) I get this:

```zsh
$ scripts/deploy.sh123.234.32.1
```

Why is it eating the space?

Environment:

* zsh 5.5.1 (x86_64-apple-darwin17.5.0)
* zsh-autosuggestions 0.4.3

Config:

```zsh
# <snip>
export ZSH_AUTOSUGGEST_USE_ASYNC=1

if type histdb > /dev/null; then
  ZSH_AUTOSUGGEST_STRATEGY=histdb # (histdb history completion)

  _zsh_autosuggest_strategy_histdb() {
    typeset -g suggestion
    suggestion=$(_histdb_query "
        SELECT commands.argv
        FROM history
          LEFT JOIN commands ON history.command_id = commands.rowid
          LEFT JOIN places ON history.place_id = places.rowid
        WHERE
          commands.argv LIKE '$(sql_escape $1)%' AND
          places.dir = '$(sql_escape $PWD)'
        GROUP BY commands.argv
        ORDER BY history.start_time desc
        LIMIT 1
    ")
  }
fi
# <snip>
```

**Comment by ericfreese** [comment] 2018-07-13 17:34
This is real weird. Would be very helpful if we could figure out what the "sometimes" condition is here.

**Comment by henrebotha** [comment] 2018-07-14 09:39
It's going to be a real knock to my productivity, but I'm going to try and get a minimal .zshrc to reproduce this.

My instinct is that this may relate to Zsh's Vi mode, which I've had other "eating" issues with in the past.

**Comment by ericfreese** [comment] 2018-07-14 18:56
Ok good luck! This is where we add the generated suggestion (POSTDISPLAY) to the buffer (BUFFER): https://github.com/zsh-users/zsh-autosuggestions/blob/master/src/widgets.zsh#L129. It's hard to imagine how that logic could be at fault, it's so simple.

I feel like I've seen similar issues caused by multibyte unicode chars (either in the prompt or in the buffer) in more recent versions of zsh so that may be another avenue to explore.

**Comment by ericfreese** [comment] 2018-09-18 05:02
Going to go ahead and close this issue. Feel free to re-open if you get more info.

**Closed by ericfreese** 2018-09-18 05:02 UTC
Labels: needs-more-info
