### ISSUE TITLE
maximum nested function level reached

### ISSUE THREAD

**Issue by metalmac** [zsh-users/zsh-autosuggestions#187] opened 2016-08-17 02:58 UTC
Hello Guys,

Have you ever ran into this issue?
Just after I installed this plugin into oh-my-zsh, and source the .zshrc file, it poped out 

_zsh_autosuggest_bound_forward-char:2: maximum nested function level reached
![zhs_plugin_issue 2016-08-17_105752](https://cloud.githubusercontent.com/assets/1448776/17723062/7eedbc9e-6469-11e6-8fe2-119985182a81.jpg)

**Comment by metalmac** [comment] 2016-08-17 03:03
In addtion, this situation occcured right after I source the .zshrc accidentally.

**Comment by metalmac** [comment] 2016-08-17 03:05
In addtion, this situation occcured right after I accidentally source the .zshrc twice.

**Comment by ericfreese** [comment] 2016-08-17 04:16
I believe this is a duplicate of #126. There are currently problems with sourcing the plugin multiple times.

**Comment by metalmac** [comment] 2016-08-17 04:26
Thanks I will check #126 ,but it seems that it doesn't have a solution to it though.

**Comment by ericfreese** [comment] 2016-08-17 04:28
Correct. Solution for now is to only source it once.

**Closed** 2016-08-24 02:16 UTC
Labels: duplicate

**Comment by albertjone** [comment] 2021-03-25 15:26
source it once, means you may start a new session and use workon or other commands and you will find it work.

**Comment by TAI-REx** [comment] 2021-08-18 13:09
Im start a new sessions and it doesnt work. any ideas folk?
