### ISSUE TITLE
Using module breaks shell

### ISSUE THREAD

**Issue by cinnamennen** [zsh-users/zsh-autosuggestions#263] opened 2017-08-07 14:38 UTC
After doing either `source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh` or `antigen bundle zsh-users/zsh-autosuggestions`, after every letter `g[: invalid integer ''` is printed. Also, a process named `(g[)` shows up in ps. An example of what might happen is as follows: (trying to type in `echo "hi"`)
```
[: invalid integer ‘’
eg[: invalid integer ‘’
ecg[: invalid integer ‘’
echg[: invalid integer ‘’
echog[: invalid integer ‘’
 g[: invalid integer ‘’
"g[: invalid integer ‘’
"hg[: invalid integer ‘’
hig[: invalid integer ‘’
i"
hi
```

**Comment by ericfreese** [comment] 2017-08-11 18:05
Can you reproduce this without loading your zsh config?

```shell
% zsh -f
%% source zsh-autosuggestions.zsh
```

If not, can you whittle down your config to find exactly which line or lines are causing this issue?

**Comment by ericfreese** [comment] 2017-08-11 19:35
Ah, I am seeing now that this is likely a duplicate of https://github.com/sorin-ionescu/prezto/issues/1382. I'm currently looking into PR #257 that should address this.

**Comment by belak** [comment] 2017-08-14 23:17
Yep, it looks like the dotphiles zsh repo was forked from prezto a few years ago, so the [gnu-utility module](https://github.com/dotphiles/dotzsh/tree/master/modules/gnu-utility) will run into the same issues we were seeing in prezto.

**Closed** 2017-12-07 01:14 UTC
