### ISSUE TITLE
Only first character of suggestion shown in Hyper

### ISSUE THREAD

**Issue by tobz-nz** [zsh-users/zsh-autosuggestions#366] opened 2018-08-29 22:22 UTC
Only the first character of suggestions are shown in [Hyper.js](https://hyper.is)

**Comment by ericfreese** [comment] 2018-08-30 03:04
Sounds like a duplicate of #243.

**Closed by ericfreese** 2018-08-30 03:04 UTC

**Comment by tobz-nz** [comment] 2018-08-30 03:09
Confirmed - yes it is the same issue, thanks.
