### ISSUE TITLE
can't work in iterm2, but work in default mac terminal.

### ISSUE THREAD

**Issue by wangyunyun** [zsh-users/zsh-autosuggestions#237] opened 2017-05-08 12:10 UTC
I use oh-my-zsh, and i installed the zsh-autosuggestions in $ZSH_CUSTOM/plugins/zsh-autosuggestions, it can't work in iterm2, but work in mac default terminal, please help me, thanks.

**Comment by mgild** [comment] 2017-05-08 15:19
Works fine for me

**Comment by pirj** [comment] 2017-05-12 23:03
Works for me. What the problem is exactly @wangyunyun?

**Comment by wangyunyun** [comment] 2017-05-17 14:05
@pirj @mgild Thanks, now work for me too, I find that the problem is caused by the theme solarized-dark, when i changed to other themes, include solarized-white, all wok fine.  now i use the japanesque theme instead.

**Comment by pirj** [comment] 2017-05-17 15:10
Good to know! Thanks for the details on how to resolve this.
Do you mind closing this one @wangyunyun ?

**Comment by wangyunyun** [comment] 2017-05-17 23:48
Of course, you can close this, the problem has been solved.

**Comment by wangyunyun** [comment] 2017-05-17 23:48
@pirj Of course, you can close this, the problem has been solved.

**Closed** 2017-05-18 01:09 UTC
Labels: support

**Comment by ortonomy** [comment] 2018-12-26 15:07
For anyone landing here: https://github.com/zsh-users/zsh-autosuggestions/issues/182

Is the fix.
