### ISSUE TITLE
Variable prompt breaks alignment

### ISSUE THREAD

**Issue by ColinArenz** [zsh-users/zsh-autosuggestions#211] opened 2016-12-14 09:47 UTC
When setting the prompt to a conditional string, its length appears to be evaluated inconsistently.  To reproduce, set prompt to the following and tab-complete any command. 
```zsh
PROMPT='%(?.$fg[white].$fg[red])> '
```

This appears to happen regardless of whether the prompt is currently formatted white or red.  Replacing the condition with either color won't reproduce the issue.

Examples using `cd` and `abcdefg` show the string repeated with a 5-character offset:
```
> cd ~ cd ~
> abcdeabcdefg
```

**Comment by ericfreese** [comment] 2017-01-19 00:45
Can you verify that you can reproduce the behavior using `zsh -f` and sourcing the plugin manually?

I'm not able to reproduce locally with the following:

```shell
% zsh -f
%% autoload -U colors && colors
%% source zsh-autosuggestions.zsh
%% PROMPT="%(?.$fg[white].$fg[red])> "
```

**Comment by ColinArenz** [comment] 2017-01-19 05:31
I do reproduce with those instructions, but it appears I can also reproduce without sourcing zsh-autosuggestions.  I suppose from that we can assume that it's an external issue with zsh itself.

```zsh
zsh -f
autoload -U colors && colors
PROMPT="%(?.$fg[white].$fg[red])> "
```

Follow this by typing `hostnam<tab><tab>` (e intentionally omitted), which yields the following result on my machine:
```
> hostnhostname
hostname     hostnamectl
```

**Comment by ericfreese** [comment] 2017-02-25 23:46
Interesting. I'm going to go ahead and close this issue since we've reproduced it without this plugin. Thanks for following up!

**Closed by ericfreese** 2017-02-25 23:46 UTC
Labels: needs-more-info
