### ISSUE TITLE
Discarded autosuggestions are not cleared when using bhilburn/powerlevel9k theme

### ISSUE THREAD

**Issue by PiQuer** [zsh-users/zsh-autosuggestions#162] opened 2016-05-28 09:27 UTC
If an autosuggestion appears but I choose to ignore it and press enter to execute everything up to the cursor (without the autosuggested part), the autosuggestion is still displayed as part of the command line, even though greyed out. For example:

```
$ echo "Hello World" "Bye"
$ echo "Hello World"
```

yields:
![screenshot_20160528_110822](https://cloud.githubusercontent.com/assets/1511250/15626475/d2aafcfe-24c5-11e6-8af4-897436f173b9.jpg)
I find this is confusing when looking back over the commands, as the actually executed commands do not always match the displayed command line. It is especially confusing for someone else watching you type.

Maybe this is intended behaviour, but I would love to have a configuration switch which tells zsh-autosuggestions to clear everything to the right of the cursor, once enter is pressed.

**Comment by ericfreese** [comment] 2016-05-28 14:41
Interesting. Trying this myself, it looks like the suggestion is cleared for me. So I'm not sure what's going on here. Can you give some more details on your system?

What OS?
What version of zsh?
What version of this plugin?

**Comment by ericfreese** [comment] 2016-05-28 15:03
One more question: Can you reproduce this without loading any other configuration? Try `zsh -f` and sourcing the plugin manually.

**Comment by PiQuer** [comment] 2016-05-28 21:53
Ok, it is my theme: bhilburn/powerlevel9k. As soon as this theme is activated, the problem occurs.
To reproduce:

    $ zsh -f
    $ source /path/to/powerlevel9k/powerlevel9k.zsh-theme
    $ source /path/to/zsh-autosuggestions/zsh-autosuggestions.zsh
    $ echo "Hello, World" "Bye"
    $ echo "Hello, World"

Arch Linux, zsh-5.2, zsh-autosuggestions-0.3.1

**Comment by ericfreese** [comment] 2016-06-06 20:08
Ok, thanks for looking deeper into this. This issue will probably be low priority for me, since I only have so much time to work on this project and I don't use that theme.

If you can figure out a change that fixes your problem without any consequences for other users, I'll be happy to merge it in. Just send a PR to merge into the `develop` branch.

**Comment by PiQuer** [comment] 2016-06-10 17:54
Thanks Eric. Probably I will also have no time for debugging any time soon, but who knows ;) If I find something I will send a PR.

**Comment by retnuh** [comment] 2016-07-20 11:00
I have pretty much the exact same problem, but it's not about my theme - I have a very simple rebinding of accept-line to reset my prompt first:

```
reset-prompt-and-accept-line() {
  zle reset-prompt
  zle accept-line
}
zle -N reset-prompt-and-accept-line
bindkey "^M" reset-prompt-and-accept-line
```

I've tried putting unset POSTDISPLAY pretty much everywhere to no avail, and calls to zle -R -c, and I can see it disappear but it then re-appears.

I'm no zsh wizard so I'm not really clear how this all works.  I may throw in a recursiveedit call to see if that helps but it's more of a guess than anything.

**Comment by retnuh** [comment] 2016-07-20 11:23
FWIW I was able to solve the problem by adding

```
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=reset-prompt-and-accept-line
```
to my snippit where I create & bind my widget.

There may be a similar widget being used in the OPs theme that could easily be added, or maybe the theme itself uses reset-prompt or something similar, and that should be in the default list of clear widgets?

**Comment by marudor** [comment] 2016-08-01 10:54
For me this fixed it with powerlevel9k
```
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=reset-prompt
```

**Comment by PiQuer** [comment] 2016-08-04 10:34
Thanks for this fix, it works!

**Comment by JonaC22** [comment] 2017-02-18 00:39
I suggest to close this issue. @PiQuer opened another in [powerlevel9k](https://github.com/bhilburn/powerlevel9k/issues/281), it was solved in https://github.com/bhilburn/powerlevel9k/commit/520eed12482b276e630d66b01a3f5852c96b6b1f and the commit is in the master branch now. There is no need of modify `ZSH_AUTOSUGGEST_CLEAR_WIDGETS` anymore. Thank you all!

**Closed** 2017-02-18 06:27 UTC
Labels: plugin-compatibility, pull-request-welcome
