### ISSUE TITLE
Configuration variables should only be set on load if they do not already exist

### ISSUE THREAD

**Issue by sudoforge** [zsh-users/zsh-autosuggestions#381] opened 2018-10-25 17:34 UTC
### Issue description

When starting Zsh, it will source the following files in this order by default (note that if `ZDOTDIR` is not set, `HOME` is used instead):

- `/etc/zsh/zshenv`
- `$ZDOTDIR/.zshenv` or `$HOME/.zshenv`
- `/etc/zsh/zprofile`
- `/etc/profile`
- `$ZDOTDIR/.zprofile` or `$HOME/.zprofile`
- `/etc/zsh/zshrc`
- `$ZDOTDIR/.zshrc` or `$HOME/.zshrc`
- `/etc/zsh/zlogin`
- `$ZDOTDIR/.zlogin` or `$HOME/.zlogin`
- `$ZDOTDIR/.zlogout` or `$HOME/.zlogout`
- `/etc/zsh/zlogout`

This plugin is sourced, or recommended to be sourced, from `$HOME/.zshrc` via all installation methods. This means that users who use a `zshenv` file (either at the system level or within the `ZDOTDIR/HOME` directory) will not be able to override the default configuration variables, which are set in `zsh-autosuggestions.zsh`.

### Solution

The default configuration variables should only be set if the variable does not already exist (and have a value) in the active environment.

**Comment by ericfreese** [comment] 2018-10-26 02:34
Thanks for your input. This looks like a duplicate of #335. Also see PR #378

**Closed by ericfreese** 2018-10-26 02:34 UTC

**Comment by sudoforge** [comment] 2018-10-26 03:04
Shoot, I did a few different searches trying to find a duplicate. Thanks for catching it.

**Comment by ericfreese** [comment] 2018-10-26 04:53
No worries! Thanks again
