### ISSUE TITLE
Complete the suggestion with Tab and not Right arrow key

### ISSUE THREAD

**Issue by Drjacky** [zsh-users/zsh-autosuggestions#707] opened 2022-09-12 17:23 UTC
### Is your feature request related to a problem? Please describe.
Right now, when the plugin suggests a word, we can accept it by pressing the right arrow key.

### Describe the solution you'd like
It'd be good to accept the suggestion by tab key as well.

**Comment by ratnanil** [comment] 2022-09-16 05:22
duplicate of #532 ?

**Closed** 2022-09-16 07:17 UTC
Labels: enhancement
