### ISSUE TITLE
Conflict with search history with text already entered at the prompt

### ISSUE THREAD

**Issue by tapyu** [zsh-users/zsh-autosuggestions#678] opened 2022-04-03 06:58 UTC
### Describe the bug
Dears,

I am using the following snippet from a [stack exchange answer](https://unix.stackexchange.com/a/97844/480687):

```
autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^[[A" history-beginning-search-backward-end
bindkey "^[[B" history-beginning-search-forward-end
```

This allows me to search through my history from the already entered text at the prompt. However, the `zsh-autosuggestions` plugin has conflicts with this snippet, which obligates me to press uparrow twice in order to search through the history

### To Reproduce
1. Put this snippet in the ~/.zshrc
1. Check that you can search from the text already entered at the prompt pressing uparrow (just once per command)
1. Install the `zsh-autosuggestions` plugin
1. Notice that now you need to press the uparrow twice per command

### Expected behavior
I would like to use the `zsh-autosuggestions` plugin and perform this search history in a minimal configuration. At the moment, I am using the [joshskidmore/zsh-fzf-history-search](https://github.com/joshskidmore/zsh-fzf-history-search) plugin to make this task, but it is more desirable to use this snippet.

Anyone has an way out or can identify what is happening?

### Desktop
```
 OS: Ubuntu 20.04 focal
 Kernel: x86_64 Linux 5.13.0-35-generic
 Shell: zsh 5.8
 DE: GNOME 3.36.5
 WM: Mutter
 CPU: Intel Core i7-9750H @ 12x 4.5GHz [44.0°C]
 GPU: Intel Corporation UHD Graphics 630 (Mobile)
NVIDIA Corporation GP107GLM [Quadro P620] (rev a1)
Plugin version: v0.7.0
```

### Additional context
- I am not using any framework to install plugins, I've been using [this approach](https://www.youtube.com/watch?v=bTLYiNvRIVI), which works elegantly to all my plugins but this one...
- Notice that this simpler snippet (it does not put the cursor at the end of the searching)
```
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward
```
works properly with the `zsh-autosuggestions` plugin. I think that the conflict is related to `history-search-end` load of the `zsh`.

**Comment by hongwen000** [comment] 2022-07-16 00:21
Same problem, I had trouble browsing history using up arrow key, twice pressing is needed, and the anoying terminal bell always rings. 

After all the search I found issue #646 suggesting adding the two bindkey commands but did not work immediately for me. After that issue #618 gave me a hint: following the direction, I identified that up arrow is encoded as `^[OA` in my workstation. 

Finally, the two lines of code solved my problem:
```
bindkey "^[OA" history-beginning-search-backward
bindkey "^[OB" history-beginning-search-forward
```

**Comment by hongwen000** [comment] 2022-07-16 00:22
Same problem, I had trouble browsing history using up arrow key, twice pressing is needed, and the anoying terminal bell always rings.

After all the search I found the issue #646 suggesting adding the two bindkey commands but did not work immediately for me. After that the issue #618 gave me a hint: following the direction, I identified that up arrow is encoded as ^[OA in my workstation.

Finally, the two lines of code solved my problem:

bindkey "^[OA" history-beginning-search-backward
bindkey "^[OB" history-beginning-search-forward

**Comment by pablospe** [comment] 2022-09-09 18:58
I also have this problem, the difference I am using Ctrl+P / Ctrl+N instead of the up/down arrows.
```
bindkey '^P' history-beginning-search-backward-end
bindkey '^N' history-beginning-search-forward-end
```

The suggestion @hongwen000 doesn't work for me. Notice that `history-beginning-search-backward` is different from `history-beginning-search-backward-end` (the **-end**). The cursor will stay in the end.

**Comment by artudytu** [comment] 2022-09-09 19:07
I had to do modifications suggested here https://github.com/zsh-users/zsh-autosuggestions/issues/619#issuecomment-904193190 . After that not only that arrows worked after pressing just once, but I had also issues with history. I could only go back like 5 commands and then it stopped working.

**Comment by pablospe** [comment] 2022-09-10 12:51
Thanks!!! I confirm this solved the issue. I added:

```
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(history-beginning-search-backward-end history-beginning-search-forward-end)
```

**Comment by ericfreese** [comment] 2023-05-26 20:31
I'm not immediately able to reproduce this. Here is what I'm trying:

```

**Comment by ericfreese** [comment] 2023-05-26 20:40
Closing as a duplicate of #619

**Closed** 2023-05-26 20:40 UTC
Labels: bug
