### ISSUE TITLE
line wrapping currupts text if prompt contains subshell with styled text

### ISSUE THREAD

**Issue by bastibe** [zsh-users/zsh-autosuggestions#325] opened 2018-05-09 11:26 UTC
If I set (for example) 

```bash
setopt prompt_subst
PROMPT='$(
  print -P "%B$PWD%b" # print PWD in bold face
)> '
```

as my PROMPT, and navigate to a nested directory that is longer than my window width, already-typed characters get corrupted.

This does not happen without the nested `print -P`

**Comment by ericfreese** [comment] 2018-05-15 20:35
I am pretty sure I'm able to reproduce this without zsh-autosuggestions plugin loaded. Looks like an upstream bug, so I'm going to go ahead and close this.

**Closed by ericfreese** 2018-05-15 20:35 UTC
