### ISSUE TITLE
Doesn't play nice with ~ when extended_glob enabled

### ISSUE THREAD

**Issue by psprint** [zsh-users/zsh-autosuggestions#168] opened 2016-06-09 08:06 UTC
Hello,
when entering a path with "~" on the beginning, then autosuggestions will keep appending text without reason:

Video:
https://asciinema.org/a/b6qo4v7o3ekvl3yw6wit0vfsa

**Comment by ericfreese** [comment] 2016-06-09 15:29
Thanks for this. I'm not able to reproduce. Can you reproduce running `zsh -f` and manually sourcing z-asug?

**Comment by psprint** [comment] 2016-06-09 15:47
Not able to reproduce. Works without colors:

https://asciinema.org/a/1d5hrip5gau6hjju4rkmjhntq

**Comment by ericfreese** [comment] 2016-06-09 15:53
Ok, so it sounds like there's some conflict with something else you're loading in your `.zshrc`. Not much I can do until we figure out what's causing the issue.

Can you work through your `.zshrc` and try to determine which settings are causing this issue?

**Comment by ericfreese** [comment] 2016-06-09 15:56
#130 may be related.

**Comment by psprint** [comment] 2016-06-09 16:14
I worked through whole `.zshrc` and `.zshenv` (had the option set there in first place), it turned out the reason is `setopt extended_glob`. If I have this in `.zshenv` or `.zshrc` then there is problem.

**Comment by ericfreese** [comment] 2016-06-09 16:54
Great, thanks for digging into this!

I'm actually seeing a slightly different behavior than your original asciinema. In the session below, I'm seeing no suggestion after typing `cd ~`, when I should be getting an appended suggestion of `/Code`. I've tried both zsh 5.0.8 and 5.2.

[![asciicast](https://asciinema.org/a/7rra2f7l06fcnyp2h4ddh8ave.png)](https://asciinema.org/a/7rra2f7l06fcnyp2h4ddh8ave)

Do you get the same behavior as above? Or are you still seeing extra incorrect text appended?

There's definitely a bug here. Just want to make sure we're on the same page.

**Comment by psprint** [comment] 2016-06-09 18:14
Yes the same behavior when with zsh -f

**Comment by ericfreese** [comment] 2016-06-10 19:22
@psprint Should be fixed on the [`fixes/tilde_extended_glob`](https://github.com/zsh-users/zsh-autosuggestions/compare/fixes/tilde_extended_glob) branch. Mind trying it out and confirming for me?

**Comment by psprint** [comment] 2016-06-10 19:48
Confirmed, with the branch I can type ~ normally 👍

**Comment by ericfreese** [comment] 2016-06-10 19:49
🍻 Cheers, thanks!

**Comment by psprint** [comment] 2016-06-10 19:52
You're welcome :)

**Comment by arianf** [comment] 2016-08-03 02:32
@ericfreese As I mentioned in my original issue #130, there are multiple characters that cause an issue, not just `~`.

When you changed the regex below from old to new, it introduced odd behavior. You fixed some with `fixes/tilde_extended_glob`, but not everything has been fixed.

```bash
"${1//(#m)[\\()\[\]|*?]/\\$MATCH}" #new 
"${1//(#m)[\][()|\\*?#<>~^]/\\$MATCH}" #old

"${1//(#m)[\\()\[\]|*?~]/\\$MATCH}" # fixes/tilde_extended_glob
```

The following characters also causes weird behavior...

```
^
#
```

**Check out this video to show how the odd behavior is: https://vid.me/nOLI**

**Closed** 2016-10-17 13:45 UTC
Labels: bug, reproduced
