### ISSUE TITLE
Suggestions work but not highlight

### ISSUE THREAD

**Issue by RemiG26** [zsh-users/zsh-autosuggestions#272] opened 2017-09-17 17:23 UTC
Hi,

I've just installing this plugin. I'm on antergos distribution with zsh 5.4.2 and oh-my-zsh. When I type `echo 'hello'` for the second time nothing appears but if I type on the right arrow the completion comes. I tried to modify the color but nothing happened.

**Comment by kutsan** [comment] 2017-09-18 01:13
In order to get help, please include your zshrc configs.

**Comment by kutsan** [comment] 2017-09-20 19:12
@m4n3z40 Bright Black color under your terminal settings configured correctly? What happens when you run this?

echo -e "\033[1;30m Hello"

Can you see the text?

**Comment by z0rc** [comment] 2017-09-20 19:12
This looks like a dupe of #262.

**Comment by kutsan** [comment] 2017-09-20 19:35
I am pretty sure this issue about the colors of your terminal. Try changing the bright black color.

**Comment by m4n3z40** [comment] 2017-09-21 21:44
Haha @kutsan is right. My color scheme was the problem. Sorry about that guys.
But thanks a lot!

**Comment by kutsan** [comment] 2017-09-21 22:21
@m4n3z40 No problem!

**Closed** 2017-09-21 23:11 UTC
